---
driver:
  name: vagrant
  network:
   - ["private_network", { ip: "10.84.101.100" }]
  customize:
    memory: 4096
    cpus: 2
  vagrantfiles:
   - test/Files/vagrant.disk.rb

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.6

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[master_test]
      - recipe[mysql_slave::default]
    attributes:
      mysql_config:
        port: '3308'